/* eslint-disable import/prefer-default-export */

export const UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGIN_SET_REDIRECT_URL = 'LOGIN_SET_REDIRECT_URL';

export const FETCH_CURRENT_USER_START = 'FETCH_CURRENT_USER_START';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_ERROR = 'FETCH_CURRENT_USER_ERROR';


export const MESSAGE_SHOW = 'MESSAGE_SHOW';
export const MESSAGE_CLOSE = 'MESSAGE_CLOSE';


export const WORKERS_LIST_FETCH_START = 'WORKERS_LIST_FETCH_START';
export const WORKERS_LIST_FETCH_SUCCESS = 'WORKERS_LIST_FETCH_SUCCESS';
export const WORKERS_LIST_FETCH_ERROR = 'WORKERS_LIST_FETCH_ERROR';

export const WORKERS_WORKER_SAVE_START = 'WORKERS_WORKER_SAVE_START';
export const WORKERS_WORKER_SAVE_SUCCESS = 'WORKERS_WORKER_SAVE_SUCCESS';
export const WORKERS_WORKER_SAVE_ERROR = 'WORKERS_WORKER_SAVE_ERROR';

export const WORKERS_REMOVE_START = 'WORKERS_REMOVE_START';
export const WORKERS_REMOVE_SUCCESS = 'WORKERS_REMOVE_SUCCESS';
export const WORKERS_REMOVE_ERROR = 'WORKERS_REMOVE_ERROR';


export const WORKERS_INSERT_START = 'WORKERS_INSERT_START';
export const WORKERS_INSERT_SUCCESS = 'WORKERS_INSERT_SUCCESS';
export const WORKERS_INSERT_ERROR = 'WORKERS_INSERT_ERROR';

export const WORKERS_WORKER_REQUEST_CREATE = 'WORKERS_WORKER_REQUEST_CREATE';
export const WORKERS_WORKER_REQUEST_EDIT = 'WORKERS_WORKER_REQUEST_EDIT';
export const WORKERS_WORKER_CANCEL_EDIT = 'WORKERS_WORKER_CANCEL_EDIT';

export const WORKERS_WORKER_FETCH_BY_CARD_START = 'WORKERS_WORKER_FETCH_BY_CARD_START';
export const WORKERS_WORKER_FETCH_BY_CARD_SUCCESS = 'WORKERS_WORKER_FETCH_BY_CARD_SUCCESS';
export const WORKERS_WORKER_FETCH_BY_CARD_ERROR = 'WORKERS_WORKER_FETCH_BY_CARD_ERROR';

export const WORKERS_QUERY_UPDATE = 'WORKERS_QUERY_UPDATE';

export const WORKERS_SELECT = 'WORKERS_SELECT';


export const MEASURERS_LIST_FETCH_START = 'MEASURERS_LIST_FETCH_START';
export const MEASURERS_LIST_FETCH_SUCCESS = 'MEASURERS_LIST_FETCH_SUCCESS';
export const MEASURERS_LIST_FETCH_ERROR = 'MEASURERS_LIST_FETCH_ERROR';
export const MEASURERS_MEASURER_SAVE_START = 'MEASURERS_MEASURER_SAVE_START';
export const MEASURERS_MEASURER_SAVE_SUCCESS = 'MEASURERS_MEASURER_SAVE_SUCCESS';
export const MEASURERS_MEASURER_SAVE_ERROR = 'MEASURERS_MEASURER_SAVE_ERROR';
export const MEASURERS_REMOVE_START = 'MEASURERS_REMOVE_START';
export const MEASURERS_REMOVE_SUCCESS = 'MEASURERS_REMOVE_SUCCESS';
export const MEASURERS_REMOVE_ERROR = 'MEASURERS_REMOVE_ERROR';
export const MEASURERS_MEASURER_REQUEST_CREATE = 'MEASURERS_MEASURER_REQUEST_CREATE';
export const MEASURERS_MEASURER_REQUEST_EDIT = 'MEASURERS_MEASURER_REQUEST_EDIT';
export const MEASURERS_MEASURER_CANCEL_EDIT = 'MEASURERS_MEASURER_CANCEL_EDIT';
export const MEASURERS_QUERY_UPDATE = 'MEASURERS_QUERY_UPDATE';
export const MEASURERS_SELECT = 'MEASURERS_SELECT';


export const MEASUREMENTS_LIST_FETCH_START = 'MEASUREMENTS_LIST_FETCH_START';
export const MEASUREMENTS_LIST_FETCH_SUCCESS = 'MEASUREMENTS_LIST_FETCH_SUCCESS';
export const MEASUREMENTS_LIST_FETCH_ERROR = 'MEASUREMENTS_LIST_FETCH_ERROR';
export const MEASUREMENTS_MEASUREMENT_SAVE_START = 'MEASUREMENTS_MEASUREMENT_SAVE_START';
export const MEASUREMENTS_MEASUREMENT_SAVE_SUCCESS = 'MEASUREMENTS_MEASUREMENT_SAVE_SUCCESS';
export const MEASUREMENTS_MEASUREMENT_SAVE_ERROR = 'MEASUREMENTS_MEASUREMENT_SAVE_ERROR';
export const MEASUREMENTS_REMOVE_START = 'MEASUREMENTS_REMOVE_START';
export const MEASUREMENTS_REMOVE_SUCCESS = 'MEASUREMENTS_REMOVE_SUCCESS';
export const MEASUREMENTS_REMOVE_ERROR = 'MEASUREMENTS_REMOVE_ERROR';
export const MEASUREMENTS_MEASUREMENT_REQUEST_CREATE = 'MEASUREMENTS_MEASUREMENT_REQUEST_CREATE';
export const MEASUREMENTS_MEASUREMENT_REQUEST_EDIT = 'MEASUREMENTS_MEASUREMENT_REQUEST_EDIT';
export const MEASUREMENTS_MEASUREMENT_CANCEL_EDIT = 'MEASUREMENTS_MEASUREMENT_CANCEL_EDIT';
export const MEASUREMENTS_QUERY_UPDATE = 'MEASUREMENTS_QUERY_UPDATE';
export const MEASUREMENTS_SELECT = 'MEASUREMENTS_SELECT';
export const MEASUREMENTS_FILTERDATA_UPDATE = 'MEASUREMENTS_FILTERDATA_UPDATE';

export const MEASUREMENTS_SEARCH_WORKERS_START = 'MEASUREMENTS_SEARCH_WORKERS_START';
export const MEASUREMENTS_SEARCH_WORKERS_SUCCESS = 'MEASUREMENTS_SEARCH_WORKERS_SUCCESS';
export const MEASUREMENTS_SEARCH_WORKERS_ERROR = 'MEASUREMENTS_SEARCH_WORKERS_ERROR';

export const MEASUREMENTS_SEARCH_MEASURERS_START = 'MEASUREMENTS_SEARCH_MEASURERS_START';
export const MEASUREMENTS_SEARCH_MEASURERS_SUCCESS = 'MEASUREMENTS_SEARCH_MEASURERS_SUCCESS';
export const MEASUREMENTS_SEARCH_MEASURERS_ERROR = 'MEASUREMENTS_SEARCH_MEASURERS_ERROR';

export const MEASUREMENTS_UPDATE_FILTER_DATA = 'MEASUREMENTS_UPDATE_FILTER_DATA';

export const FILE_CREATE_ITEM_START = 'FILE_CREATE_ITEM_START';
export const FILE_CREATE_ITEM_SUCCESS = 'FILE_CREATE_ITEM_SUCCESS';
export const FILE_CREATE_ITEM_ERROR = 'FILE_CREATE_ITEM_ERROR';
export const FILE_UPLOAD_START = 'FILE_UPLOAD_START';
export const FILE_UPLOAD_SUCCESS = 'FILE_UPLOAD_SUCCESS';
export const FILE_UPLOAD_ERROR = 'FILE_UPLOAD_ERROR';
